version: '3.8'

services:
  # Spacy Service (Python/FastAPI)
  spacy-service:
    build:
      context: ./spacy-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./spacy-service:/app
    networks:
      - contentstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Node.js Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SPACY_SERVICE_URL=http://spacy-service:8000
    depends_on:
      spacy-service:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - contentstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - contentstack-network

networks:
  contentstack-network:
    driver: bridge

volumes:
  node_modules: